# Generated by Django 5.1.3 on 2024-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
