# Generated by Django 5.1.3 on 2024-11-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_client_user_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='client',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
