# Generated by Django 5.1.3 on 2024-11-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_client_email_remove_client_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
