# Generated by Django 5.1.3 on 2024-11-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
